### ISSUE TITLE
RFE: Properly Place Source Files

### ISSUE THREAD

**Issue by TPS** [MrKrzYch00/krzydefc#1]
@MrKrzYch00 Thanks for releasing the binaries here on GitHub.  However, the links to the "Source Code" contain nothing but the README in the Zip/TGZ.  Please, could you properly place the source in the git repo (along w/ LICENSE.md), or, alternatively (if you wish _not_ to release the source) remove those "Source Code" links?

**Comment by MrKrzYch00** [comment]
They are automatically generated and cannot be deleted. Source is closed (check readme).
